# Generated by Django 3.2 on 2022-12-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('context', models.TextField(max_length=500)),
                ('petwalk', models.CharField(choices=[('o', '1'), ('x', '0')], max_length=1)),
                ('petwalknum', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
