# Generated by Django 3.2 on 2022-12-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalnameing', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccination', models.DateField(blank=True, null=True)),
                ('heartworm', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('hospital_name', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=200)),
                ('days', models.DateField()),
                ('required', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
